### ISSUE TITLE
about python format

### ISSUE THREAD

**Issue by alanspike** [MingSun-Tse/Efficient-NeRF#1]
1. Have we used any python formatter, such as [YAPF](https://github.com/google/yapf), to automatically format the code?
2. For each python file, could we first write the system libs, then the libs we installed, and lastly our implemented libs, with an empty line between them? For example:

> import os, sys
> 
> import numpy as np
> import torch
> 
> from run_nerf_helpers import *

**Comment by MingSun-Tse** [comment]
1. Used yapf to format the code: `yapf --in-place --recursive --style="{indent_width: 4}" *.py`
2. For all the .py in the root folder, I have adjusted the import order as suggested

**Comment by alanspike** [comment]
Thanks! If you use some IDEs like vscode, they can do the formatting for you automatically.
