### ISSUE TITLE
about comments

### ISSUE THREAD

**Issue by alanspike** [MingSun-Tse/Efficient-NeRF#2]
Could we delete the comments that are used for debugging? For example, the comments [here](https://github.com/MingSun-Tse/Efficient-NeRF/blob/b59b82cd6417a6801ddfea2c4cff8dba01dc0d05/run_nerf.py#L10) and [here](https://github.com/MingSun-Tse/Efficient-NeRF/blob/b59b82cd6417a6801ddfea2c4cff8dba01dc0d05/run_nerf.py#L103-L113) seem not useful.

**Comment by MingSun-Tse** [comment]
run_nerf.py is the original nerf code; we have integrated it to run_nerf_raybased.py. So run_nerf.py and run_nerf_helpers.py now are removed.
