### ISSUE TITLE
about pre-trained models

### ISSUE THREAD

**Issue by alanspike** [MingSun-Tse/Efficient-NeRF#4]
Do we want to provide the pre-trained teacher models and our r2l models?

**Comment by MingSun-Tse** [comment]
Yes, we provide the pretrained teacher and our R2L models

**Comment by alanspike** [comment]
Okay. There is no link from [Download our trained models here.
](https://github.com/MingSun-Tse/Efficient-NeRF#3-test-our-trained-r2l-models)

**Comment by MingSun-Tse** [comment]
Will upload them soon in the final step to create official releases

**Comment by MingSun-Tse** [comment]
Pretrained models uploaded and update the README
