### ISSUE TITLE
Do we still need torchsearchsorted?

### ISSUE THREAD

**Issue by alanspike** [MingSun-Tse/Efficient-NeRF#5]
Do we still need this [folder](https://github.com/MingSun-Tse/Efficient-NeRF/tree/huan_dev/torchsearchsorted)? It seems the folder is not necessary from this [pr](https://github.com/yenchenlin/nerf-pytorch/pull/35)?

**Comment by MingSun-Tse** [comment]
Use the new implementation; the folder still kept for now, will be removed.
