### ISSUE TITLE
about models

### ISSUE THREAD

**Issue by alanspike** [MingSun-Tse/Efficient-NeRF#6]
1. Do we want to keep the [unet](https://github.com/MingSun-Tse/Efficient-NeRF/tree/cf114d2a6e539d159a16a5bc72ac329bd96d2bdb/model/unet) folder?
2. Do we need all the ray based variants in [nerf_raybased.py](https://github.com/MingSun-Tse/Efficient-NeRF/blob/huan_dev/model/nerf_raybased.py)?
3. Do we need the [NeRF_v2](https://github.com/MingSun-Tse/Efficient-NeRF/blob/e0ffa70342c5c62a29f3c287106434d1141fafea/run_nerf_raybased_helpers.py#L236) in run_nerf_raybased_helpers.py?

**Comment by MingSun-Tse** [comment]
removed these useless models
